#define _GNU_SOURCE
#define _POSIX_C_SOURCE 200809L

#ifdef __clang__
#pragma clang diagnostic ignored "-Wnon-literal-null-conversion"
#endif

#include <assert.h>
#include <complex.h>
#include <math.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define atomic(T) _Atomic(T)
#define thread_local _Thread_local

#include "config.h"
#include "random.h"
#include "utility.h"

#include "tmpconfig.h" // temporary file: generated by Python

typedef int64_t int64;

enum {
	SAVE_TRAJECTORY = true,
	nullptr = 0,
};


enum JumpType {
	JUMP_COLLECTIVE_SPIN_DEPHASING,
	JUMP_COLLECTIVE_SPIN_LOSS,
	JUMP_COLLECTIVE_SPIN_GAIN,

 	JUMP_SPIN_DEPHASING_SAME_J,
 	JUMP_SPIN_DEPHASING_LOWER_J,
 	JUMP_SPIN_DEPHASING_UPPER_J,

	JUMP_SPIN_LOSS_SAME_J,
	JUMP_SPIN_LOSS_LOWER_J,
	JUMP_SPIN_LOSS_UPPER_J,

 	JUMP_SPIN_GAIN_SAME_J,
 	JUMP_SPIN_GAIN_LOWER_J,
 	JUMP_SPIN_GAIN_UPPER_J,

	JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J,
	JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J,
	JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J,

 	JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J,
 	JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J,
 	JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J,

	JUMP_PHOTON_LOSS,
	JUMP_COUNT,

	EFFECTIVE_HAMILTONIAN = JUMP_COUNT,
};

// Young Tableau of wavefunction:
//
// [1111111111][222222]
// [2222222]
//
// GT Pattern:
//
// (a b)
// ( c )
//
// Constraints:
// a + b = N
// a >= c >= b
// 
// Populations:
// spin_down = c
// spin_up = N - c

struct TrajectoryState {
	int64 row1, row2; // Young diagram shape

	// wavefunction
	double time;
	double time_step;

	// state is just two numbers!
	int64 n;
	int64 a;

	// two time correlation parameters
	complex double molmer_factor;
};


complex double (*tfunc)[TsLength];

// must include after type definitions
#include "tmp.h" // generated by Python


// PI jump weightings
double precompute_e_factor(int64 r1, int64 r2) { return (r1 == r2) ? 0 : (double)(r1 + r2 + 2) / ((r1 - r2)*(r1 - r2 + 2)); }
double precompute_f_factor(int64 r1, int64 r2) { return (r1 == r2) ? 0 : (double)(r1 + 1) / ((r1 - r2) * (r1 - r2 + 1)); }
double precompute_g_factor(int64 r1, int64 r2) { return (double)(r2) / ((r1 - r2 + 1)*(r1 - r2 + 2)); }


// Select a jump (or effective Hamiltonian) at random using probabilities in the jump table.
//
int64 select_random_jump(double jump_table[]) {
	double r = random_uniform();
	double seen_probability = 0;

	for (int64 choice = 0; choice < JUMP_COUNT; ++choice) {
		seen_probability += jump_table[choice];
		if (r < seen_probability) return choice;
	}

	// If no jump has been selected then we evolve using the effective Hamiltonian.
	return EFFECTIVE_HAMILTONIAN;
}


thread_local int64 simulation_index;
complex double *initial_state;
double initial_j_sector;
uint64_t prefix;
complex double (*output_matrix)[ExpectationOps][OutputCount];

struct TrajectoryState simulate_trajectory(struct TrajectoryState *initial, double start_time, double end_time, bool output) {
	int64 row1 = (int)(NumberOfEmitters/2.0f + initial_j_sector);
	int64 row2 = NumberOfEmitters - row1;

	struct TrajectoryState state = {
		.row1 = row1,
		.row2 = row2,

		.time = start_time,
		.time_step = 0,

		.n = 0,
		.a = 0,

		.molmer_factor = 1,
	};

	if (initial) memcpy(&state, initial, sizeof state);
	else {
		for (int64 n = state.row2; n <= state.row1; ++n) {
			if (cnorm(initial_state[n]) > 0) {
				state.n = n;
				break;
			}
		}
	}

	double e_factor = precompute_e_factor(state.row1, state.row2);
	double f_factor = precompute_f_factor(state.row1, state.row2);
	double g_factor = precompute_g_factor(state.row1, state.row2);

	int64 step = 0;
	double next_write = state.time;

	while (state.time <= config.EndTime) {
		double jump_table[JUMP_COUNT] = {0};

		int64 jpm = state.row1 - state.n; // J+M
		int64 jmm = state.n - state.row2; // J-M
		double m = 0.5f * (NumberOfEmitters - 2*state.n);

		jump_table[JUMP_SPIN_DEPHASING_SAME_J]  = m * m;
		jump_table[JUMP_SPIN_DEPHASING_LOWER_J] = jmm*jpm;
		jump_table[JUMP_SPIN_DEPHASING_UPPER_J] = (jmm + 1)*(jpm + 1);

		jump_table[JUMP_SPIN_LOSS_SAME_J]  = (jmm + 1)*(jpm);
		jump_table[JUMP_SPIN_LOSS_LOWER_J] = (jpm - 1)*(jpm);
		jump_table[JUMP_SPIN_LOSS_UPPER_J] = (jmm + 1)*(jmm + 2);

		jump_table[JUMP_SPIN_GAIN_SAME_J]  = (jpm + 1)*(jmm);
		jump_table[JUMP_SPIN_GAIN_LOWER_J] = (jmm - 1)*(jmm);
		jump_table[JUMP_SPIN_GAIN_UPPER_J] = (jpm + 1)*(jpm + 2);

		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J]  = (jmm + 1)*(jpm) * (state.a + 1);
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J] = (jpm - 1)*(jpm) * (state.a + 1);
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J] = (jmm + 1)*(jmm + 2) * (state.a + 1);

		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J]  = (jpm + 1)*(jmm) * state.a;
		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J] = (jmm - 1)*(jmm) * state.a;
		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J] = (jpm + 1)*(jpm + 2) * state.a;

		jump_table[JUMP_PHOTON_LOSS] = state.a;

		// scale jump probabilities by loss rates
		jump_table[JUMP_COLLECTIVE_SPIN_DEPHASING] = jump_table[JUMP_SPIN_DEPHASING_SAME_J] * config.CollectiveDephasingRate;
		jump_table[JUMP_COLLECTIVE_SPIN_LOSS] = jump_table[JUMP_SPIN_LOSS_SAME_J] * config.CollectiveEmissionRate;
		jump_table[JUMP_COLLECTIVE_SPIN_GAIN] = jump_table[JUMP_SPIN_GAIN_SAME_J] * config.CollectivePumpingRate;
		jump_table[JUMP_SPIN_DEPHASING_SAME_J]  *= 4*config.DephasingRate * e_factor;
		jump_table[JUMP_SPIN_DEPHASING_LOWER_J] *= 4*config.DephasingRate * f_factor;
		jump_table[JUMP_SPIN_DEPHASING_UPPER_J] *= 4*config.DephasingRate * g_factor;
		jump_table[JUMP_SPIN_LOSS_SAME_J]  *= config.EmissionRate * e_factor;
		jump_table[JUMP_SPIN_LOSS_LOWER_J] *= config.EmissionRate * f_factor;
		jump_table[JUMP_SPIN_LOSS_UPPER_J] *= config.EmissionRate * g_factor;
		jump_table[JUMP_SPIN_GAIN_SAME_J]  *= config.PumpingRate * e_factor;
		jump_table[JUMP_SPIN_GAIN_LOWER_J] *= config.PumpingRate * f_factor;
		jump_table[JUMP_SPIN_GAIN_UPPER_J] *= config.PumpingRate * g_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J]  *= config.CavityEmissionRate * e_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J] *= config.CavityEmissionRate * f_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J] *= config.CavityEmissionRate * g_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J]  *= config.CavityAbsorptionRate * e_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J] *= config.CavityAbsorptionRate * f_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J] *= config.CavityAbsorptionRate * g_factor;
		jump_table[JUMP_PHOTON_LOSS] *= config.PhotonLossRate;

		double total_decay_rate = 0;	
		for (int64 i = 0; i < JUMP_COUNT; ++i) total_decay_rate += jump_table[i];

		assert(total_decay_rate > 0 && "zero or negative decay rate!");

		double r = random_uniform();
		state.time_step = -log(r) / total_decay_rate;

		// scale jump probabilities by dt
		for (int64 i = 0; i < JUMP_COUNT; ++i) jump_table[i] /= total_decay_rate;
		state.time += state.time_step;

		while (output && state.time >= next_write) {
			complex double expectation[ExpectationOps] = {0};
			compute_expectation_values(&state, expectation, state.n, state.a);

			for (int64 op = 0; op < ExpectationOps; ++op) {
				expectation[op] *= state.molmer_factor;
				output_matrix[simulation_index - 1][op][step] = expectation[op];
			}

			step += 1;
			next_write = start_time + (end_time - start_time) * step / (OutputCount - 1);
 		}

		int64 choice = select_random_jump(jump_table);
		int64 row1_copy = state.row1;

		switch (choice) {
			case JUMP_COLLECTIVE_SPIN_DEPHASING: break;
			case JUMP_COLLECTIVE_SPIN_LOSS: state.n += 1; break;
			case JUMP_COLLECTIVE_SPIN_GAIN: state.n -= 1; break;

			case JUMP_SPIN_DEPHASING_SAME_J:  break;
			case JUMP_SPIN_DEPHASING_LOWER_J: state.row1 -= 1; state.row2 += 1; break;
			case JUMP_SPIN_DEPHASING_UPPER_J: state.row1 += 1; state.row2 -= 1; break;

			case JUMP_SPIN_LOSS_SAME_J:  state.n += 1; break;
			case JUMP_SPIN_LOSS_LOWER_J: state.n += 1; state.row1 -= 1; state.row2 += 1; break;
			case JUMP_SPIN_LOSS_UPPER_J: state.n += 1; state.row1 += 1; state.row2 -= 1; break;

			case JUMP_SPIN_GAIN_SAME_J:  state.n -= 1; break;
			case JUMP_SPIN_GAIN_LOWER_J: state.n -= 1; state.row1 -= 1; state.row2 += 1; break;
			case JUMP_SPIN_GAIN_UPPER_J: state.n -= 1; state.row1 += 1; state.row2 -= 1; break;

			case JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J:  state.n += 1; state.a += 1; break;
			case JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J: state.n += 1; state.a += 1; state.row1 -= 1; state.row2 += 1; break;
			case JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J: state.n += 1; state.a += 1; state.row1 += 1; state.row2 -= 1; break;

			case JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J:  state.n -= 1; state.a -= 1; break;
			case JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J: state.n -= 1; state.a -= 1; state.row1 -= 1; state.row2 += 1; break;
			case JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J: state.n -= 1; state.a -= 1; state.row1 += 1; state.row2 -= 1; break;

			case JUMP_PHOTON_LOSS: state.a -= 1; break;
			case EFFECTIVE_HAMILTONIAN: assert(0 && "unreachable!");
		}

		// if jump occured to different J sector
		if (state.row1 != row1_copy) {
			e_factor = precompute_e_factor(state.row1, state.row2);
			f_factor = precompute_f_factor(state.row1, state.row2);
			g_factor = precompute_g_factor(state.row1, state.row2);
		}
	}

	return state;
}


// Multithreading code.
//
atomic(int) thread_id;
atomic(int) thread_pool;
atomic(int) threads_complete;
atomic(int) total_millis;

#define CLEAR_LINE "\r\x1b[2K"

void *thread_worker() {
	int64 id = atomic_fetch_add(&thread_id, 1);
	set_random_seed(id | prefix);

	int64 next;

	while ((next = atomic_fetch_add(&thread_pool, -1)) > 0) {
		double begin = get_time_from_os();

		simulation_index = next;
		simulate_trajectory(nullptr, config.StartTime, config.EndTime, true);

		double end = get_time_from_os();

		int64 millis = (int)(1000.0f * (end - begin));
		double total_seconds = (atomic_fetch_add(&total_millis, millis) + millis) / 1000.0f;

		int64 complete = atomic_fetch_add(&threads_complete, 1) + 1;
		double average_seconds = total_seconds / complete;

		fprintf(stderr, CLEAR_LINE "Trajectory [%lld/%d] completed, average time: %.3f seconds.", complete, config.TrajectoryCount, average_seconds);
	}

	return nullptr;
}


void run_trajectories(uint64_t hash_id, double j_sector, complex double *inital_state_data, complex double (*__tfunc)[TsLength],
                      double _correlation_time, complex double (*_output_matrix)[ExpectationOps][OutputCount])
{
	thread_pool = config.TrajectoryCount;
	threads_complete = 0;
	thread_id = 0;
	total_millis = 0;
	tfunc = __tfunc;
	output_matrix = _output_matrix;

	assert(_correlation_time < 0 && "internal error!");

	initial_state = inital_state_data;
	initial_j_sector = j_sector;
	prefix = hash_id;

	pthread_t threads[ThreadCount];

	for (int64 i = 0; i < ThreadCount; ++i) pthread_create(&threads[i], nullptr, thread_worker, nullptr);
	for (int64 i = 0; i < ThreadCount; ++i) pthread_join(threads[i], nullptr);
	fprintf(stderr, "\n");
}

