#define _GNU_SOURCE
#define _POSIX_C_SOURCE 200809L

#ifdef __clang__
#pragma clang diagnostic ignored "-Wnon-literal-null-conversion"
#endif

#include <assert.h>
#include <complex.h>
#include <math.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define atomic(T) _Atomic(T)
#define thread_local _Thread_local

#include "config.h"
#include "random.h"
#include "utility.h"

#include "tmpconfig.h" // temporary file: generated by Python


enum {
	SAVE_TRAJECTORY = true,
	nullptr = 0,
};


enum JumpType {
	JUMP_COLLECTIVE_SPIN_DEPHASING,
	JUMP_COLLECTIVE_SPIN_LOSS,
	JUMP_COLLECTIVE_SPIN_GAIN,

 	JUMP_SPIN_DEPHASING_SAME_J,
 	JUMP_SPIN_DEPHASING_LOWER_J,
 	JUMP_SPIN_DEPHASING_UPPER_J,

	JUMP_SPIN_LOSS_SAME_J,
	JUMP_SPIN_LOSS_LOWER_J,
	JUMP_SPIN_LOSS_UPPER_J,

 	JUMP_SPIN_GAIN_SAME_J,
 	JUMP_SPIN_GAIN_LOWER_J,
 	JUMP_SPIN_GAIN_UPPER_J,

	JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J,
	JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J,
	JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J,

 	JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J,
 	JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J,
 	JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J,

	JUMP_PHOTON_LOSS,
	JUMP_COUNT,

	EFFECTIVE_HAMILTONIAN = JUMP_COUNT,
};

// Young Tableau of wavefunction:
//
// [1111111111][222222]
// [2222222]
//
// GT Pattern:
//
// (a b)
// ( c )
//
// Constraints:
// a + b = N
// a >= c >= b
// 
// Populations:
// spin_down = c
// spin_up = N - c

typedef complex float WaveVector[NumberOfEmitters + 1][CavityTruncation];

struct TrajectoryState {
	int row1, row2; // Young diagram shape
 	int rowa, rowb; // truncated diagram (with tolerance to ignore low norm states)
	int mina, maxa; // dynamical scaling of photon mode

	float time;
	float time_step;
	WaveVector *wave;
};


struct WaveVectorAllocation {
	complex float __padding1[PaddingWidth*CavityTruncation];
	WaveVector wave;
	complex float __padding2[PaddingWidth*CavityTruncation];
};


// must include after type definitions
#include "tmp.h" // generated by Python


// PI jump weightings
float precompute_e_factor(int r1, int r2) { return (r1 == r2) ? 0 : (float)(r1 + r2 + 2) / ((r1 - r2)*(r1 - r2 + 2)); }
float precompute_f_factor(int r1, int r2) { return (r1 == r2) ? 0 : (float)(r1 + 1) / ((r1 - r2) * (r1 - r2 + 1)); }
float precompute_g_factor(int r1, int r2) { return (float)(r2) / ((r1 - r2 + 1)*(r1 - r2 + 2)); }


// Select a jump (or effective Hamiltonian) at random using probabilities in the jump table.
//
int select_random_jump(float jump_table[]) {
	float r = random_uniform();
	float seen_probability = 0;

	for (int choice = 0; choice < JUMP_COUNT; ++choice) {
		seen_probability += jump_table[choice];
		if (r < seen_probability) return choice;
	}

	// If no jump has been selected then we evolve using the effective Hamiltonian.
	return EFFECTIVE_HAMILTONIAN;
}


// Compute linear effective Hamiltonian step
//
void linear_hamiltonian_integration_step(WaveVector dest, WaveVector source, struct TrajectoryState *state) {
	memset(dest, 0, sizeof(WaveVector));

	for (int n = state->rowb; n <= state->rowa; ++n) { // number of spin down
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jpm = state->row1 - n; // J+M
			int jmm = n - state->row2; // J-M
			float m2 = (NumberOfEmitters - 2*n);

			// Jump dagger jump terms from effective Hamiltonian
			dest[n][a] -= source[n][a] * state->time_step/2 * (
				config.PhotonLossRate * a +
				config.DephasingRate * NumberOfEmitters +
				config.EmissionRate * (NumberOfEmitters - n) +
				config.PumpingRate * n +
				config.CollectiveDephasingRate * m2*m2 +
				config.CollectiveEmissionRate * (jmm + 1)*(jpm) +
				config.CollectivePumpingRate * (jpm + 1)*(jmm) +
				config.CavityEmissionRate * (jmm + 1)*(jpm) * (a + 1) +
				config.CavityAbsorptionRate * (jpm + 1)*(jmm) * a
			);

			hamiltonian_term(dest, source, state, n, a);
		}
	}
}


// Higher order exponetial evolution with Wiener fluctuation for QSD
//
void evolve_under_H_eff(WaveVector wave, struct TrajectoryState *state) {
	// In this case of an exponential and linear Hamiltonian, the Runge-Kutta method
	// is identical to a Taylor series expansion, so this is performed directly for efficiency.

	static thread_local struct WaveVectorAllocation _a, _b; // Create two temporary vectors using double-buffering technique.
	complex float (*a)[CavityTruncation] = wave; // Controlled by pointers which are cheap to swap.
	complex float (*b)[CavityTruncation] = _b.wave;

	int factorial = 1;

	for (int i = 1; i <= config.RungeKuttaPoly; ++i) {
		linear_hamiltonian_integration_step(b, a, state); // |b> = -i Heff dt |a>
		factorial *= i;

		// accumulate Taylor series expansion
		float factor = 1.0f / factorial;

		for (int n = state->rowb; n <= state->rowa; ++n) {
			for (int a = state->mina; a <= state->maxa; ++a) {
				wave[n][a] += factor * b[n][a];
			}
		}

		if (i == 1) a = _a.wave; // a is temporarily set to wave for first iteration to avoid a copy

		// perform double-buffering: swap pointers
		complex float (*tmp)[CavityTruncation] = a;
		a = b;
		b = tmp;
	}
}


// Implementation of Quantum Jumps:
// The coefficients of jumps are ignored as the states will be renormalised afterwards.
// The phase is also ignored as it doesn't determine the dynamics (Lindblad jumps are invariant under phase rotations).

void jump_spin_dephasing_same_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			wave[n][a] *= 0.5f * (NumberOfEmitters - 2*n);
		}
	}
}


void jump_spin_dephasing_lower_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jpm = state->row1 - n; // J + M
			int jmm = n - state->row2; // J - M

			wave[n][a] *= sqrtf(jmm*jpm);
		}
	}

	state->row1 -= 1;
	state->row2 += 1;
}


void jump_spin_dephasing_upper_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jpm = state->row1 - n; // J + M
			int jmm = n - state->row2; // J - M

			wave[n][a] *= sqrtf((jmm + 1)*(jpm + 1));
		}
	}

	state->row1 += 1;
	state->row2 -= 1;
}


void jump_spin_loss_same_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowa; n >= state->rowb; --n) { // iterate backwards due to overlap
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jpm = state->row1 - n; // J + M
			int jmm = n - state->row2; // J - M

			wave[n + 1][a] = sqrtf((jmm + 1)*jpm) * wave[n][a];
		}
	}

	state->rowa += 1;
	state->rowb += 1;
}


void jump_spin_loss_lower_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowa; n >= state->rowb; --n) { // iterate backwards due to overlap
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jpm = state->row1 - n; // J + M

			wave[n + 1][a] = sqrtf((jpm - 1)*(jpm)) * wave[n][a];
		}
	}

	state->row1 -= 1;
	state->row2 += 1;
	state->rowa += 1;
	state->rowb += 1;
}


void jump_spin_loss_upper_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowa; n >= state->rowb; --n) { // iterate backwards due to overlap
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jmm = n - state->row2; // J - M

			wave[n + 1][a] = sqrtf((jmm + 1)*(jmm + 2)) * wave[n][a];
		}
	}

	state->row1 += 1;
	state->row2 -= 1;
	state->rowa += 1;
	state->rowb += 1;
}


void jump_spin_gain_same_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb + 1; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jpm = state->row1 - n; // J + M
			int jmm = n - state->row2; // J - M

			wave[n - 1][a] = sqrtf((jpm + 1)*jmm) * wave[n][a];
		}
	}

	state->rowa -= 1;
	state->rowb -= 1;
}


void jump_spin_gain_lower_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb + 2; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jmm = n - state->row2; // J - M

			wave[n - 1][a] = sqrtf((jmm - 1)*(jmm)) * wave[n][a];
		}
	}

	state->row1 -= 1;
	state->row2 += 1;
	state->rowa -= 1;
	state->rowb -= 1;
}


void jump_spin_gain_upper_j(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			int jpm = state->row1 - n; // J + M

			wave[n - 1][a] = sqrtf((jpm + 1)*(jpm + 2)) * wave[n][a];
		}
	}

	state->row1 += 1;
	state->row2 -= 1;
	state->rowa -= 1;
	state->rowb -= 1;
}


void jump_photon_loss(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = 1; a < CavityTruncation; ++a) {
			wave[n][a - 1] = sqrtf(a) * wave[n][a];
		}
		wave[n][CavityTruncation - 1] = 0;
	}
}


void jump_photon_gain(WaveVector wave, struct TrajectoryState *state) {
	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = CavityTruncation - 1; a > 0; --a) {
			wave[n][a] = sqrtf(a) * wave[n][a - 1];
		}
		wave[n][0] = 0;
	}
}


float normalize_state(WaveVector wave, struct TrajectoryState *state) {
	float norm = 0;

	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			norm += cnormf(wave[n][a]);
		}
	}

	assert(norm && "Invalid state: has norm of zero");
	float scale = 1.0f / sqrtf(norm);

	for (int n = state->rowb; n <= state->rowa; ++n) {
		for (int a = state->mina; a <= state->maxa; ++a) {
			wave[n][a] *= scale;
		}
	}

	return norm;
}


thread_local int simulation_index;
complex float *initial_state;
float initial_j_sector;
uint64_t prefix;


struct TrajectoryState simulate_trajectory(float total_time, struct TrajectoryState *initial) {
	static thread_local struct WaveVectorAllocation wave_alloc;

	// (row1 - row2) = 2J
	//  row1 + row2 = N
	//  row1 = N/2 + J

	int row1 = (int)(NumberOfEmitters/2.0f + initial_j_sector);
	int row2 = NumberOfEmitters - row1;

	struct TrajectoryState state = {
		.row1 = row1,
		.row2 = row2,

		.rowa = row1,
		.rowb = row2,

		.mina = 0,
		.maxa = CavityTruncation - 1,

		.time = 0,
		.wave = &wave_alloc.wave,
	};

	if (initial) memcpy(&state, initial, sizeof state);
	else {
		memset(*state.wave, 0, sizeof *state.wave);

		for (int n = state.rowb; n <= state.rowa; ++n) {
			(*state.wave)[n][0] = initial_state[n];
		}
	}

	complex float (*wave)[CavityTruncation] = *state.wave;

	float e_factor = precompute_e_factor(state.row1, state.row2);
	float f_factor = precompute_f_factor(state.row1, state.row2);
	float g_factor = precompute_g_factor(state.row1, state.row2);

	float tick_size = total_time / OutputCount;
	float next_write = 0; 

	char filename[100];
	sprintf(filename, "trajectory-%llx-%d.txt", prefix, simulation_index);

	FILE *log = fopen(filename, "wb");
	assert(log && "failed to open file to save trajectory");

	while (state.time < total_time) {
 		if (state.time + state.time_step > next_write) {
			complex float expectation[ExpectationOps] = {0};
			compute_expectation_values(wave, &state, expectation);

			fprintf(log, "%f", state.time);

			for (int op = 0; op < ExpectationOps; ++op) {
				fprintf(log, "\t%g\t%g", crealf(expectation[op]), cimagf(expectation[op]));
			}

			float photon_density[CavityTruncation] = {0};
			float spin_density[NumberOfEmitters + 1] = {0};

			for (int n = state.rowb; n <= state.rowa; ++n) {
				for (int a = state.mina; a <= state.maxa; ++a) {
					photon_density[a] += cnormf(wave[n][a]);
					spin_density[n] += cnormf(wave[n][a]);
				}
			}

			for (int a = 0; a < CavityTruncation; ++a) {
				fprintf(log, "\t%g", photon_density[a]);
			}

			for (int n = 0; n <= NumberOfEmitters; ++n) {
				fprintf(log, "\t%g", spin_density[n]);
			}

			fprintf(log, "\n");
 			next_write += tick_size;
 		}

		float jump_table[JUMP_COUNT] = {0};

		for (int n = state.rowb; n <= state.rowa; ++n) {
			for (int a = state.mina; a <= state.maxa; ++a) {
				float norm = cnormf(wave[n][a]);

				int jpm = state.row1 - n; // J+M
				int jmm = n - state.row2; // J-M
				float m = 0.5f * (NumberOfEmitters - 2*n);

				jump_table[JUMP_SPIN_DEPHASING_SAME_J]  += norm * m * m;
				jump_table[JUMP_SPIN_DEPHASING_LOWER_J] += norm * jmm*jpm;
				jump_table[JUMP_SPIN_DEPHASING_UPPER_J] += norm * (jmm + 1)*(jpm + 1);

				jump_table[JUMP_SPIN_LOSS_SAME_J]  += norm * (jmm + 1)*(jpm);
				jump_table[JUMP_SPIN_LOSS_LOWER_J] += norm * (jpm - 1)*(jpm);
				jump_table[JUMP_SPIN_LOSS_UPPER_J] += norm * (jmm + 1)*(jmm + 2);

				jump_table[JUMP_SPIN_GAIN_SAME_J]  += norm * (jpm + 1)*(jmm);
				jump_table[JUMP_SPIN_GAIN_LOWER_J] += norm * (jmm - 1)*(jmm);
				jump_table[JUMP_SPIN_GAIN_UPPER_J] += norm * (jpm + 1)*(jpm + 2);

				jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J]  += norm * (jmm + 1)*(jpm) * (a + 1);
				jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J] += norm * (jpm - 1)*(jpm) * (a + 1);
				jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J] += norm * (jmm + 1)*(jmm + 2) * (a + 1);

 				jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J]  += norm * (jpm + 1)*(jmm) * a;
 				jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J] += norm * (jmm - 1)*(jmm) * a;
 				jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J] += norm * (jpm + 1)*(jpm + 2) * a;

				jump_table[JUMP_PHOTON_LOSS] += norm * a;
			}
		}

		// scale jump probabilities by loss rates
		jump_table[JUMP_COLLECTIVE_SPIN_DEPHASING] = jump_table[JUMP_SPIN_DEPHASING_SAME_J] * config.CollectiveDephasingRate;
		jump_table[JUMP_COLLECTIVE_SPIN_LOSS] = jump_table[JUMP_SPIN_LOSS_SAME_J] * config.CollectiveEmissionRate;
		jump_table[JUMP_COLLECTIVE_SPIN_GAIN] = jump_table[JUMP_SPIN_GAIN_SAME_J] * config.CollectivePumpingRate;
		jump_table[JUMP_SPIN_DEPHASING_SAME_J]  *= 4*config.DephasingRate * e_factor;
		jump_table[JUMP_SPIN_DEPHASING_LOWER_J] *= 4*config.DephasingRate * f_factor;
		jump_table[JUMP_SPIN_DEPHASING_UPPER_J] *= 4*config.DephasingRate * g_factor;
		jump_table[JUMP_SPIN_LOSS_SAME_J]  *= config.EmissionRate * e_factor;
		jump_table[JUMP_SPIN_LOSS_LOWER_J] *= config.EmissionRate * f_factor;
		jump_table[JUMP_SPIN_LOSS_UPPER_J] *= config.EmissionRate * g_factor;
		jump_table[JUMP_SPIN_GAIN_SAME_J]  *= config.PumpingRate * e_factor;
		jump_table[JUMP_SPIN_GAIN_LOWER_J] *= config.PumpingRate * f_factor;
		jump_table[JUMP_SPIN_GAIN_UPPER_J] *= config.PumpingRate * g_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J]  *= config.CavityEmissionRate * e_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J] *= config.CavityEmissionRate * f_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J] *= config.CavityEmissionRate * g_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J]  *= config.CavityAbsorptionRate * e_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J] *= config.CavityAbsorptionRate * f_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J] *= config.CavityAbsorptionRate * g_factor;
		jump_table[JUMP_PHOTON_LOSS] *= config.PhotonLossRate;

		float max_factor = 1.0f; // min of 1 to guarantee max dt of tolerance
		for (int i = 0; i < JUMP_COUNT; ++i) max_factor = fmaxf(max_factor, jump_table[i]);

		state.time_step = config.JumpTolerance / max_factor;
		state.time += state.time_step;

		// scale jump probabilities by dt
		for (int i = 0; i < JUMP_COUNT; ++i) jump_table[i] *= state.time_step;

		int choice = select_random_jump(jump_table);
		int row1_copy = state.row1;

		switch (choice) {
			case JUMP_COLLECTIVE_SPIN_DEPHASING: jump_spin_dephasing_same_j(wave, &state); break;
			case JUMP_COLLECTIVE_SPIN_LOSS: jump_spin_loss_same_j(wave, &state); break;
			case JUMP_COLLECTIVE_SPIN_GAIN: jump_spin_gain_same_j(wave, &state); break;

			case JUMP_SPIN_DEPHASING_SAME_J:  jump_spin_dephasing_same_j(wave, &state);  break;
			case JUMP_SPIN_DEPHASING_LOWER_J: jump_spin_dephasing_lower_j(wave, &state); break;
			case JUMP_SPIN_DEPHASING_UPPER_J: jump_spin_dephasing_upper_j(wave, &state); break;

			case JUMP_SPIN_LOSS_SAME_J:  jump_spin_loss_same_j(wave, &state);  break;
			case JUMP_SPIN_LOSS_LOWER_J: jump_spin_loss_lower_j(wave, &state); break;
			case JUMP_SPIN_LOSS_UPPER_J: jump_spin_loss_upper_j(wave, &state); break;

			case JUMP_SPIN_GAIN_SAME_J:  jump_spin_gain_same_j(wave, &state);  break;
			case JUMP_SPIN_GAIN_LOWER_J: jump_spin_gain_lower_j(wave, &state); break;
			case JUMP_SPIN_GAIN_UPPER_J: jump_spin_gain_upper_j(wave, &state); break;

			case JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J:  jump_spin_loss_same_j(wave, &state);  jump_photon_gain(wave, &state); break;
			case JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J: jump_spin_loss_lower_j(wave, &state); jump_photon_gain(wave, &state); break;
			case JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J: jump_spin_loss_upper_j(wave, &state); jump_photon_gain(wave, &state); break;

 			case JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J:  jump_spin_gain_same_j(wave, &state);  jump_photon_loss(wave, &state); break;
 			case JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J: jump_spin_gain_lower_j(wave, &state); jump_photon_loss(wave, &state); break;
 			case JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J: jump_spin_gain_upper_j(wave, &state); jump_photon_loss(wave, &state); break;

			case JUMP_PHOTON_LOSS: jump_photon_loss(wave, &state); break;

			case EFFECTIVE_HAMILTONIAN: evolve_under_H_eff(wave, &state); break;
		}

		if (state.rowa > state.row1) state.rowa = state.row1;
		if (state.rowb < state.row2) state.rowb = state.row2;

		if (state.row1 != row1_copy) {
			e_factor = precompute_e_factor(state.row1, state.row2);
			f_factor = precompute_f_factor(state.row1, state.row2);
			g_factor = precompute_g_factor(state.row1, state.row2);
		}

		normalize_state(wave, &state);

		// expand bounds of spin-space as necessary
		float min_inner = 0, min_outer = 0;
		float max_inner = 0, max_outer = 0;

		for (int a = state.mina; a <= state.maxa; ++a) {
			min_outer += cnormf((*state.wave)[state.rowb][a]);
			max_outer += cnormf((*state.wave)[state.rowa][a]);
			min_inner += cnormf((*state.wave)[state.rowb + 1][a]);
			max_inner += cnormf((*state.wave)[state.rowa - 1][a]);
		}

		if ((min_inner + min_outer) < config.ShrinkTolerance) state.rowb += 1;
		if ((max_inner + max_outer) < config.ShrinkTolerance) state.rowa -= 1;

		if (min_outer > config.ShrinkTolerance && state.rowb > state.row2) {
			state.rowb -= 1;
			memset((*state.wave)[state.rowb], 0, sizeof (*state.wave)[0]);
		}

		if (max_outer > config.ShrinkTolerance && state.rowa < state.row1) {
			state.rowa += 1;
			memset((*state.wave)[state.rowa], 0, sizeof (*state.wave)[0]);
		}

		// do same for photon mode
		min_inner = 0, min_outer = 0;
		max_inner = 0, max_outer = 0;

		for (int n = state.rowb; n <= state.rowa; ++n) {
			min_outer += cnormf((*state.wave)[n][state.mina]);
			max_outer += cnormf((*state.wave)[n][state.maxa]);
			min_inner += cnormf((*state.wave)[n][state.mina + 1]);
			max_inner += cnormf((*state.wave)[n][state.maxa - 1]);
		}

		if ((min_inner + min_outer) < config.ShrinkTolerance) state.mina += 1;
		if ((max_inner + max_outer) < config.ShrinkTolerance) state.maxa -= 1;

		if (min_outer > config.ShrinkTolerance && state.mina > 0) {
			state.mina -= 1;
			for (int n = state.rowb; n <= state.rowa; ++n) (*state.wave)[n][state.mina] = 0;
		}

		if (max_outer > config.ShrinkTolerance && state.maxa + 1 < CavityTruncation) {
			state.maxa += 1;
			for (int n = state.rowb; n <= state.rowa; ++n) (*state.wave)[n][state.maxa] = 0;
		}
	}

   	if (log) fclose(log);
	return state;
}


// Multithreading code.
//
atomic(int) thread_id;
atomic(int) thread_pool;
atomic(int) threads_complete;
atomic(int) total_millis;

#define CLEAR_LINE "\r\x1b[2K"

void *thread_worker() {
	int id = atomic_fetch_add(&thread_id, 1);
	set_random_seed(id);

	int next;

	while ((next = atomic_fetch_add(&thread_pool, -1)) > 0) {
		double begin = get_time_from_os();
		simulation_index = next;

		simulate_trajectory(config.TimeSpan, nullptr);
		double end = get_time_from_os();

		int millis = (int)(1000.0f * (end - begin));
		float total_seconds = (atomic_fetch_add(&total_millis, millis) + millis) / 1000.0f;

		int complete = atomic_fetch_add(&threads_complete, 1) + 1;
		float average_seconds = total_seconds / complete;

		fprintf(stderr, CLEAR_LINE "Trajectory [%d/%d] completed, average time: %.3f seconds.", complete, config.TrajectoryCount, average_seconds);
	}

	return nullptr;
}


void run_trajectories(uint64_t hash_id, float j_sector, complex float *inital_state_data) {
	thread_pool = config.TrajectoryCount;
	threads_complete = 0;
	thread_id = 0;
	total_millis = 0;

	initial_state = inital_state_data;
	initial_j_sector = j_sector;
	prefix = hash_id;

	pthread_t threads[ThreadCount];

	for (int i = 0; i < ThreadCount; ++i) pthread_create(&threads[i], nullptr, thread_worker, nullptr);
	for (int i = 0; i < ThreadCount; ++i) pthread_join(threads[i], nullptr);
	fprintf(stderr, "\n");
}

