#define _GNU_SOURCE
#define _POSIX_C_SOURCE 200809L

#ifdef __clang__
#pragma clang diagnostic ignored "-Wnon-literal-null-conversion"
#endif

#include <assert.h>
#include <complex.h>
#include <math.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define atomic(T) _Atomic(T)
#define thread_local _Thread_local

#include "config.h"
#include "random.h"
#include "utility.h"

#include "tmpconfig.h" // temporary file: generated by Python

typedef int64_t int64;

enum {
	SAVE_TRAJECTORY = true,
	nullptr = 0,
};


enum JumpType {
	JUMP_COLLECTIVE_SPIN_DEPHASING,
	JUMP_COLLECTIVE_SPIN_LOSS,
	JUMP_COLLECTIVE_SPIN_GAIN,

 	JUMP_SPIN_DEPHASING_SAME_J,
 	JUMP_SPIN_DEPHASING_LOWER_J,
 	JUMP_SPIN_DEPHASING_UPPER_J,

	JUMP_SPIN_LOSS_SAME_J,
	JUMP_SPIN_LOSS_LOWER_J,
	JUMP_SPIN_LOSS_UPPER_J,

 	JUMP_SPIN_GAIN_SAME_J,
 	JUMP_SPIN_GAIN_LOWER_J,
 	JUMP_SPIN_GAIN_UPPER_J,

	JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J,
	JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J,
	JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J,

 	JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J,
 	JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J,
 	JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J,

	JUMP_PHOTON_LOSS,
	JUMP_COUNT,

	EFFECTIVE_HAMILTONIAN = JUMP_COUNT,
};

// Young Tableau of wavefunction:
//
// [1111111111][222222]
// [2222222]
//
// GT Pattern:
//
// (a b)
// ( c )
//
// Constraints:
// a + b = N
// a >= c >= b
// 
// Populations:
// spin_down = c
// spin_up = N - c

typedef complex double WaveVector[NumberOfEmitters + 1];

struct TrajectoryState {
	int64 row1, row2; // Young diagram shape
 	int64 rowa, rowb; // truncated diagram (with tolerance to ignore low norm states)

	// wavefunction
	double time;
	double time_step;
	WaveVector *wave;

	// conserved number of excitations (by Heff)
	int64 excitations;

	// two time correlation parameters
	complex double molmer_factor;
};


struct WaveVectorAllocation {
	complex double __padding1[(SpinWidth + 1)*CavityTruncation];
	WaveVector wave;
	complex double __padding2[(SpinWidth + 1)*CavityTruncation];
};


complex double (*tfunc)[TsLength];

// must include after type definitions
#include "tmp.h" // generated by Python


// PI jump weightings
double precompute_e_factor(int64 r1, int64 r2) { return (r1 == r2) ? 0 : (double)(r1 + r2 + 2) / ((r1 - r2)*(r1 - r2 + 2)); }
double precompute_f_factor(int64 r1, int64 r2) { return (r1 == r2) ? 0 : (double)(r1 + 1) / ((r1 - r2) * (r1 - r2 + 1)); }
double precompute_g_factor(int64 r1, int64 r2) { return (double)(r2) / ((r1 - r2 + 1)*(r1 - r2 + 2)); }


// Select a jump (or effective Hamiltonian) at random using probabilities in the jump table.
//
int64 select_random_jump(double jump_table[]) {
	double r = random_uniform();
	double seen_probability = 0;

	for (int64 choice = 0; choice < JUMP_COUNT; ++choice) {
		seen_probability += jump_table[choice];
		if (r < seen_probability) return choice;
	}

	// If no jump has been selected then we evolve using the effective Hamiltonian.
	return EFFECTIVE_HAMILTONIAN;
}


// Compute linear effective Hamiltonian step
//
void linear_hamiltonian_integration_step(WaveVector dest, WaveVector source, struct TrajectoryState *state) {
	memset(dest, 0, sizeof(WaveVector));

	for (int64 n = state->rowb; n <= state->rowa; ++n) { // number of spin down
		int64 a = state->excitations - (NumberOfEmitters - n);
		if (a < 0) {
			assert(cnorm(source[n]) == 0);
			continue;
		}

		int64 jpm = state->row1 - n; // J+M
		int64 jmm = n - state->row2; // J-M
		double m2 = (NumberOfEmitters - 2*n);

		// Jump dagger jump terms from effective Hamiltonian
		dest[n] -= source[n] * state->time_step/2 * (
			config.PhotonLossRate * a + //(a + cnorm(state->annihilation)) + //(norm shrinkage)
			// config.DephasingRate * NumberOfEmitters + //(norm shrinkage)
			config.EmissionRate * (NumberOfEmitters - n) +
			config.PumpingRate * n +
			config.CollectiveDephasingRate * m2*m2 +
			config.CollectiveEmissionRate * (jmm + 1)*(jpm) +
			config.CollectivePumpingRate * (jpm + 1)*(jmm) +
			config.CavityEmissionRate * (NumberOfEmitters - n) * (a + 1) +
			config.CavityAbsorptionRate * n * a
		);

		hamiltonian_term(dest, source, state, n, a);
	}
}


// Higher order exponetial evolution with Wiener fluctuation for QSD
//
void evolve_under_H_eff(WaveVector wave, struct TrajectoryState *state) {
	// In this case of an exponential and linear Hamiltonian, the Runge-Kutta method
	// is identical to a Taylor series expansion, so this is performed directly for efficiency.

	static thread_local struct WaveVectorAllocation _a, _b; // Create two temporary vectors using double-buffering technique.
	complex double *a = wave; // Controlled by pointers which are cheap to swap.
	complex double *b = _b.wave;

	int64 factorial = 1;

	for (int64 i = 1; i <= config.RungeKuttaPoly; ++i) {
		linear_hamiltonian_integration_step(b, a, state); // |b> = -i Heff dt |a>
		factorial *= i;

		// accumulate Taylor series expansion
		double factor = 1.0f / factorial;

		for (int64 n = state->rowb; n <= state->rowa; ++n) {
			wave[n] += factor * b[n];
		}

		if (i == 1) a = _a.wave; // a is temporarily set to wave for first iteration to avoid a copy

		// perform double-buffering: swap pointers
		complex double *tmp = a;
		a = b;
		b = tmp;
	}
}


// Implementation of Quantum Jumps:
// The coefficients of jumps are ignored as the states will be renormalised afterwards.
// The phase is also ignored as it doesn't determine the dynamics (Lindblad jumps are invariant under phase rotations).

void jump_spin_dephasing_same_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		wave[n] *= 0.5f * (NumberOfEmitters - 2*n);
	}
}


void jump_spin_dephasing_lower_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		int64 jpm = state->row1 - n; // J + M
		int64 jmm = n - state->row2; // J - M

		wave[n] *= sqrt(jmm*jpm);
	}

	state->row1 -= 1;
	state->row2 += 1;
}


void jump_spin_dephasing_upper_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		int64 jpm = state->row1 - n; // J + M
		int64 jmm = n - state->row2; // J - M

		wave[n] *= sqrt((jmm + 1)*(jpm + 1));
	}

	state->row1 += 1;
	state->row2 -= 1;
}


void jump_spin_loss_same_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowa; n >= state->rowb; --n) { // iterate backwards due to overlap
		int64 jpm = state->row1 - n; // J + M
		int64 jmm = n - state->row2; // J - M

		wave[n + 1] = sqrt((jmm + 1)*jpm) * wave[n];
	}

	wave[state->rowb] = 0;
	state->excitations -= 1;
}


void jump_spin_loss_lower_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowa; n >= state->rowb; --n) { // iterate backwards due to overlap
		int64 jpm = state->row1 - n; // J + M

		wave[n + 1] = sqrt((jpm - 1)*(jpm)) * wave[n];
	}

	wave[state->rowb] = 0;

	state->row1 -= 1;
	state->row2 += 1;
	state->excitations -= 1;
}


void jump_spin_loss_upper_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowa; n >= state->rowb; --n) { // iterate backwards due to overlap
		int64 jmm = n - state->row2; // J - M

		wave[n + 1] = sqrt((jmm + 1)*(jmm + 2)) * wave[n];
	}

	wave[state->rowb] = 0;

	state->row1 += 1;
	state->row2 -= 1;
	state->excitations -= 1;
}


void jump_spin_gain_same_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		int64 jpm = state->row1 - n; // J + M
		int64 jmm = n - state->row2; // J - M

		wave[n - 1] = sqrt((jpm + 1)*jmm) * wave[n];
	}

	wave[state->rowa] = 0;
	state->excitations += 1;
}


void jump_spin_gain_lower_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
			int64 jmm = n - state->row2; // J - M

			wave[n - 1] = sqrt((jmm - 1)*(jmm)) * wave[n];
	}

	wave[state->rowa] = 0;

	state->row1 -= 1;
	state->row2 += 1;
	state->excitations += 1;
}


void jump_spin_gain_upper_j(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		int64 jpm = state->row1 - n; // J + M

		wave[n - 1] = sqrt((jpm + 1)*(jpm + 2)) * wave[n];
	}

	wave[state->rowa] = 0;

	state->row1 += 1;
	state->row2 -= 1;
	state->excitations += 1;
}


void jump_photon_loss(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		int64 a = state->excitations - (NumberOfEmitters - n);
		if (a < 0) continue;
		wave[n] *= sqrt(a);
	}

	state->excitations -= 1;
}


void jump_photon_gain(WaveVector wave, struct TrajectoryState *state) {
	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		int64 a = state->excitations - (NumberOfEmitters - n);
		if (a < 0) continue;
		wave[n] *= sqrt(a + 1);
	}

	state->excitations += 1;

}


double normalize_state(WaveVector wave, struct TrajectoryState *state) {
	double norm = 0;

	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		norm += cnorm(wave[n]);
	}

	assert(norm && "Invalid state: has norm of zero");
	double scale = 1.0f / sqrt(norm);

	for (int64 n = state->rowb; n <= state->rowa; ++n) {
		wave[n] *= scale;
	}

	return norm;
}


thread_local int64 simulation_index;
complex double *initial_state;
double initial_j_sector;
uint64_t prefix;
complex double (*output_matrix)[ExpectationOps][OutputCount];

struct TrajectoryState simulate_trajectory(struct TrajectoryState *initial, double start_time, double end_time, bool output) {
	static thread_local struct WaveVectorAllocation wave_alloc;

	int64 row1 = (int)(NumberOfEmitters/2.0f + initial_j_sector);
	int64 row2 = NumberOfEmitters - row1;

	struct TrajectoryState state = {
		.row1 = row1,
		.row2 = row2,

		.rowa = row1,
		.rowb = row2,

		.time = start_time,
		.time_step = 0,
		.wave = &wave_alloc.wave,

		// .excitations set below
		.molmer_factor = 1,
	};

	if (initial) memcpy(&state, initial, sizeof state);
	else {
		memset(*state.wave, 0, sizeof *state.wave);

		for (int64 n = state.rowb; n <= state.rowa; ++n) {
			(*state.wave)[n] = initial_state[n];
			if (cnorm(initial_state[n]) != 0) state.excitations = (NumberOfEmitters - n);
		}
	}

	complex double *wave = *state.wave;

	double e_factor = precompute_e_factor(state.row1, state.row2);
	double f_factor = precompute_f_factor(state.row1, state.row2);
	double g_factor = precompute_g_factor(state.row1, state.row2);

	int64 step = 0;
	double next_write = state.time; 

	while (state.time <= config.EndTime) {
		if (output && state.time == next_write) {
			complex double expectation[ExpectationOps] = {0};

			for (int64 n = state.rowb; n <= state.rowa; ++n) {
				int64 a = state.excitations - (NumberOfEmitters - n);
				if (a < 0) continue;
				compute_expectation_values(wave, &state, expectation, n, a);
			}

			for (int64 op = 0; op < ExpectationOps; ++op) {
				expectation[op] *= state.molmer_factor;
				output_matrix[simulation_index - 1][op][step] = expectation[op];
			}

			step += 1;
 			next_write = start_time + (end_time - start_time) * step / (OutputCount - 1);
 		}

		double jump_table[JUMP_COUNT] = {0};

		for (int64 n = state.rowb; n <= state.rowa; ++n) {
			int64 a = state.excitations - (NumberOfEmitters - n);
			if (a < 0) continue;

			double norm = cnorm(wave[n]);

			int64 jpm = state.row1 - n; // J+M
			int64 jmm = n - state.row2; // J-M
			double m = 0.5f * (NumberOfEmitters - 2*n);

			jump_table[JUMP_SPIN_DEPHASING_SAME_J]  += norm * m * m;
			jump_table[JUMP_SPIN_DEPHASING_LOWER_J] += norm * jmm*jpm;
			jump_table[JUMP_SPIN_DEPHASING_UPPER_J] += norm * (jmm + 1)*(jpm + 1);

			jump_table[JUMP_SPIN_LOSS_SAME_J]  += norm * (jmm + 1)*(jpm);
			jump_table[JUMP_SPIN_LOSS_LOWER_J] += norm * (jpm - 1)*(jpm);
			jump_table[JUMP_SPIN_LOSS_UPPER_J] += norm * (jmm + 1)*(jmm + 2);

			jump_table[JUMP_SPIN_GAIN_SAME_J]  += norm * (jpm + 1)*(jmm);
			jump_table[JUMP_SPIN_GAIN_LOWER_J] += norm * (jmm - 1)*(jmm);
			jump_table[JUMP_SPIN_GAIN_UPPER_J] += norm * (jpm + 1)*(jpm + 2);

			if (a + 1 < CavityTruncation) {
				jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J]  += norm * (jmm + 1)*(jpm) * (a + 1);
				jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J] += norm * (jpm - 1)*(jpm) * (a + 1);
				jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J] += norm * (jmm + 1)*(jmm + 2) * (a + 1);
			}

			jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J]  += norm * (jpm + 1)*(jmm) * a;
			jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J] += norm * (jmm - 1)*(jmm) * a;
			jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J] += norm * (jpm + 1)*(jpm + 2) * a;

			jump_table[JUMP_PHOTON_LOSS] += norm * a;
		}

		// scale jump probabilities by loss rates
		jump_table[JUMP_COLLECTIVE_SPIN_DEPHASING] = jump_table[JUMP_SPIN_DEPHASING_SAME_J] * config.CollectiveDephasingRate;
		jump_table[JUMP_COLLECTIVE_SPIN_LOSS] = jump_table[JUMP_SPIN_LOSS_SAME_J] * config.CollectiveEmissionRate;
		jump_table[JUMP_COLLECTIVE_SPIN_GAIN] = jump_table[JUMP_SPIN_GAIN_SAME_J] * config.CollectivePumpingRate;
		jump_table[JUMP_SPIN_DEPHASING_SAME_J]  *= 4*config.DephasingRate * e_factor;
		jump_table[JUMP_SPIN_DEPHASING_LOWER_J] *= 4*config.DephasingRate * f_factor;
		jump_table[JUMP_SPIN_DEPHASING_UPPER_J] *= 4*config.DephasingRate * g_factor;
		jump_table[JUMP_SPIN_LOSS_SAME_J]  *= config.EmissionRate * e_factor;
		jump_table[JUMP_SPIN_LOSS_LOWER_J] *= config.EmissionRate * f_factor;
		jump_table[JUMP_SPIN_LOSS_UPPER_J] *= config.EmissionRate * g_factor;
		jump_table[JUMP_SPIN_GAIN_SAME_J]  *= config.PumpingRate * e_factor;
		jump_table[JUMP_SPIN_GAIN_LOWER_J] *= config.PumpingRate * f_factor;
		jump_table[JUMP_SPIN_GAIN_UPPER_J] *= config.PumpingRate * g_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J]  *= config.CavityEmissionRate * e_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J] *= config.CavityEmissionRate * f_factor;
		jump_table[JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J] *= config.CavityEmissionRate * g_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J]  *= config.CavityAbsorptionRate * e_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J] *= config.CavityAbsorptionRate * f_factor;
 		jump_table[JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J] *= config.CavityAbsorptionRate * g_factor;
		jump_table[JUMP_PHOTON_LOSS] *= config.PhotonLossRate;

		double max_factor = 1.0f; // min of 1 to guarantee max dt of tolerance
		for (int64 i = 0; i < JUMP_COUNT; ++i) max_factor = fmax(max_factor, jump_table[i]);

		state.time_step = config.JumpTolerance / max_factor;

		if (output && state.time + state.time_step >= next_write) { // do not remove!
			state.time_step = next_write - state.time;
		}

		// scale jump probabilities by dt
		for (int64 i = 0; i < JUMP_COUNT; ++i) jump_table[i] *= state.time_step;
		state.time += state.time_step;

		int64 choice = select_random_jump(jump_table);
		int64 row1_copy = state.row1;

		switch (choice) {
			case JUMP_COLLECTIVE_SPIN_DEPHASING: jump_spin_dephasing_same_j(wave, &state); break;
			case JUMP_COLLECTIVE_SPIN_LOSS: jump_spin_loss_same_j(wave, &state); break;
			case JUMP_COLLECTIVE_SPIN_GAIN: jump_spin_gain_same_j(wave, &state); break;

			case JUMP_SPIN_DEPHASING_SAME_J:  jump_spin_dephasing_same_j(wave, &state);  break;
			case JUMP_SPIN_DEPHASING_LOWER_J: jump_spin_dephasing_lower_j(wave, &state); break;
			case JUMP_SPIN_DEPHASING_UPPER_J: jump_spin_dephasing_upper_j(wave, &state); break;

			case JUMP_SPIN_LOSS_SAME_J:  jump_spin_loss_same_j(wave, &state);  break;
			case JUMP_SPIN_LOSS_LOWER_J: jump_spin_loss_lower_j(wave, &state); break;
			case JUMP_SPIN_LOSS_UPPER_J: jump_spin_loss_upper_j(wave, &state); break;

			case JUMP_SPIN_GAIN_SAME_J:  jump_spin_gain_same_j(wave, &state);  break;
			case JUMP_SPIN_GAIN_LOWER_J: jump_spin_gain_lower_j(wave, &state); break;
			case JUMP_SPIN_GAIN_UPPER_J: jump_spin_gain_upper_j(wave, &state); break;

			case JUMP_SPIN_LOSS_PHOTON_GAIN_SAME_J:  jump_photon_gain(wave, &state); jump_spin_loss_same_j(wave, &state);  break;
			case JUMP_SPIN_LOSS_PHOTON_GAIN_LOWER_J: jump_photon_gain(wave, &state); jump_spin_loss_lower_j(wave, &state); break;
			case JUMP_SPIN_LOSS_PHOTON_GAIN_UPPER_J: jump_photon_gain(wave, &state); jump_spin_loss_upper_j(wave, &state); break;

			case JUMP_SPIN_GAIN_PHOTON_LOSS_SAME_J:  jump_photon_loss(wave, &state); jump_spin_gain_same_j(wave, &state);  break;
			case JUMP_SPIN_GAIN_PHOTON_LOSS_LOWER_J: jump_photon_loss(wave, &state); jump_spin_gain_lower_j(wave, &state); break;
			case JUMP_SPIN_GAIN_PHOTON_LOSS_UPPER_J: jump_photon_loss(wave, &state); jump_spin_gain_upper_j(wave, &state); break;

			case JUMP_PHOTON_LOSS: jump_photon_loss(wave, &state); break;
			case EFFECTIVE_HAMILTONIAN: evolve_under_H_eff(wave, &state); break;
		}

		assert(state.excitations >= 0);

		// if jump occured to different J sector
		if (state.row1 != row1_copy) {
			e_factor = precompute_e_factor(state.row1, state.row2);
			f_factor = precompute_f_factor(state.row1, state.row2);
			g_factor = precompute_g_factor(state.row1, state.row2);
		}

		// expand valid region
		state.rowb -= config.RungeKuttaPoly * SpinWidth;
		state.rowa += config.RungeKuttaPoly * SpinWidth;

		// prevent exceeding bounds of Hilbert space
		if (state.rowb < state.row2)        state.rowb = state.row2;
		if (state.rowa > state.row1)        state.rowa = state.row1;

		// normalize the wavefunction
		normalize_state(wave, &state);

		// then shrink to fit
		for (;; ++state.rowb) {
			double norm = cnorm(wave[state.rowb]);
			if (norm >= config.ShrinkTolerance) break;
			wave[state.rowb] = 0;
		}

		for (;; --state.rowa) {
			double norm = cnorm(wave[state.rowa]);
			if (norm >= config.ShrinkTolerance) break;
			wave[state.rowa] = 0;
		}

		// small-expand valid region
		state.rowb -= SpinWidth;
		state.rowa += SpinWidth;

		// prevent exceeding bounds of Hilbert space
		if (state.rowb < state.row2)        state.rowb = state.row2;
		if (state.rowa > state.row1)        state.rowa = state.row1;
	}

	return state;
}

// Two time correlation as described by Molmer et al.
// this method is used to avoid inner products between states displaced by different amounts

double correlation_time;

void two_time_correlation() {
	static thread_local struct WaveVectorAllocation second_wave;
	struct TrajectoryState psi = simulate_trajectory(nullptr, 0, correlation_time, false);

	// split wave function into 4 states, and then evolve trajectories from there...
	// in this case hat(a) = hat(b) + alpha

	complex double factor = 1;

	for (int64 split = 0; split < 4; ++split) { // cycle through 1, i, -1, -i
		struct TrajectoryState phi = psi;
		phi.wave = &second_wave.wave;

		memcpy(phi.wave, psi.wave, sizeof(WaveVector));

		for (int64 n = phi.rowb; n <= phi.rowa; ++n) {
			int64 a = phi.excitations - (NumberOfEmitters - n);
			if (a < 0) continue;

			collapse_operator(*phi.wave, *psi.wave, &phi, factor, n, a);
		}

		double norm = normalize_state(*phi.wave, &phi);
		phi.molmer_factor = conjf(factor) * norm;
		phi.time = config.StartTime;

		simulation_index += 1;
		simulate_trajectory(&phi, config.StartTime, config.EndTime, true);

		factor *= I;
	}
}


// Multithreading code.
//
atomic(int) thread_id;
atomic(int) thread_pool;
atomic(int) threads_complete;
atomic(int) total_millis;

#define CLEAR_LINE "\r\x1b[2K"

bool correlation = 0;

void *thread_worker() {
	int64 id = atomic_fetch_add(&thread_id, 1);
	set_random_seed(id | prefix);

	int64 next;

	while ((next = atomic_fetch_add(&thread_pool, -1)) > 0) {
		double begin = get_time_from_os();

		if (correlation) {
			simulation_index = 4 * (next - 1);
			two_time_correlation();
		} else {
			simulation_index = next;
			simulate_trajectory(nullptr, config.StartTime, config.EndTime, true);
		}

		double end = get_time_from_os();

		int64 millis = (int)(1000.0f * (end - begin));
		double total_seconds = (atomic_fetch_add(&total_millis, millis) + millis) / 1000.0f;

		int64 complete = atomic_fetch_add(&threads_complete, 1) + 1;
		double average_seconds = total_seconds / complete;

		fprintf(stderr, CLEAR_LINE "Trajectory [%lld/%d] completed, average time: %.3f seconds.", complete, config.TrajectoryCount, average_seconds);
	}

	return nullptr;
}


void run_trajectories(uint64_t hash_id, double j_sector, complex double *inital_state_data, complex double (*__tfunc)[TsLength],
                      double _correlation_time, complex double (*_output_matrix)[ExpectationOps][OutputCount])
{
	thread_pool = config.TrajectoryCount;
	threads_complete = 0;
	thread_id = 0;
	total_millis = 0;
	tfunc = __tfunc;
	output_matrix = _output_matrix;

	correlation_time = _correlation_time;
	correlation = correlation_time >= 0;

	initial_state = inital_state_data;
	initial_j_sector = j_sector;
	prefix = hash_id;

	pthread_t threads[ThreadCount];

	for (int64 i = 0; i < ThreadCount; ++i) pthread_create(&threads[i], nullptr, thread_worker, nullptr);
	for (int64 i = 0; i < ThreadCount; ++i) pthread_join(threads[i], nullptr);
	fprintf(stderr, "\n");
}

